_BASE_: "/root/nnknguyen/baseline/data_generator/densepose/configs/base.yaml"
MODEL:
  WEIGHTS: "/root/nnknguyen/baseline/data_generator/densepose/ckpt/final.pkl"
  RESNETS:
    DEPTH: 101
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseDeepLabHead"
SOLVER:
  MAX_ITER: 130000
  STEPS: (100000, 120000)